name: Daily build
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup node-json
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.0'

      - name: Install Dependencies
        run: npm install
           